In [3]:
# Logistic Regression

# Step 1: Importing the essential libraries
# numpy → for numerical operations (arrays, math functions)
# matplotlib → for plotting graphs and visualizations
# pandas → for handling datasets (tables, CSV files, etc.)
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# Importing the dataset
# Step 2: Load the dataset into a pandas DataFrame
# 'Social_Network_Ads.csv' contains user details (Age, Estimated Salary) 
# and whether they purchased the product (Purchased = 1 or 0).
dataset = pd.read_csv('Social_Network_Ads.csv')

# Step 3: Separate features (X) and target (y)
# X → input features (Age, Estimated Salary)
# iloc[:, :-1] → selects all rows, all columns except the last one
X = dataset.iloc[:, :-1].values

# y → output label (Purchased)
# iloc[:, -1] → selects all rows, only the last column
y = dataset.iloc[:, -1].values

In [5]:
dataset.head(10)

,Age,EstimatedSalary,Purchased
0,19,19000,0
1,35,20000,0
2,26,43000,0
3,27,57000,0
4,19,76000,0
5,27,58000,0
6,27,84000,0
7,32,150000,1
8,25,33000,0
9,35,65000,0


##  About the Dataset: Social Network Ads

This dataset contains information about users and whether they purchased a product after seeing an advertisement.  
It has **three columns**:

- **Age** → The age of the user (numeric feature).  
- **EstimatedSalary** → The estimated annual salary of the user (numeric feature).  
- **Purchased** → Target variable (binary outcome):
  - `0` → User did not purchase
  - `1` → User purchased

###  Example Records
| Age | EstimatedSalary | Purchased |
|-----|----------------|-----------|
| 19  | 19000          | 0         |
| 35  | 20000          | 0         |
| 27  | 57000          | 0         |
| 32  | 150000         | 1         |

###  Learning Goal
We will use **Logistic Regression** to predict whether a user will purchase (`Purchased = 1`) or not (`Purchased = 0`) based on their **Age** and **EstimatedSalary**.


In [6]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [7]:
# Splitting the dataset into the Training set and Test set
# Step 4: Divide the dataset into two parts:
# - Training set → used to train the Logistic Regression model
# - Test set → used to evaluate how well the model performs on unseen data

from sklearn.model_selection import train_test_split

# test_size = 0.25 → 25% of the data will be used for testing, 75% for training
# random_state = 0 → ensures reproducibility (same split every time you run)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
# Printing the results to understand the split
print("Training Features (X_train):")
print(X_train)

Training Features (X_train):
[[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]
 [    35  25000]
 [    35  50000]
 [    42  73000]
 [    47  49000]
 [    59  29000]
 [    49  65000]
 [    45 131000]
 [    31  89000]
 [    46  82000]
 [    47  51000]
 [    26  15000]
 [    60 102000]
 [    38 112000]
 [    40 107000]
 [    42  53000]
 [    35  59000]
 [    48  41000]
 [    48 134000]
 [    38 113000]
 [    29 148000]
 [    26  15000]
 [    60  42000]
 [    24  19000]
 [    42 149000]
 [    46  96000]
 [    28  59000]
 [    39  96000]
 [    28  89000]
 [    41  72000]
 [    45  26000]
 [    33  69000]
 [    20  82000]
 [    31  74000]
 [    42  80000]
 [    35  72000]
 [    33 149000]
 [    40  71000]
 [    51 146000]
 [    46  79000]
 [    35  75000]
 [    38  51000]
 [    36  75000]
 [    37  78000]
 [    38  61000]
 [    60 108000]
 [    20  82000]
 [    57  74000]
 [

In [9]:
print("\nTraining Labels (y_train):")
print(y_train)


Training Labels (y_train):
[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [10]:
print("\nTest Features (X_test):")
print(X_test)


Test Features (X_test):
[[    30  87000]
 [    38  50000]
 [    35  75000]
 [    30  79000]
 [    35  50000]
 [    27  20000]
 [    31  15000]
 [    36 144000]
 [    18  68000]
 [    47  43000]
 [    30  49000]
 [    28  55000]
 [    37  55000]
 [    39  77000]
 [    20  86000]
 [    32 117000]
 [    37  77000]
 [    19  85000]
 [    55 130000]
 [    35  22000]
 [    35  47000]
 [    47 144000]
 [    41  51000]
 [    47 105000]
 [    23  28000]
 [    49 141000]
 [    28  87000]
 [    29  80000]
 [    37  62000]
 [    32  86000]
 [    21  88000]
 [    37  79000]
 [    57  60000]
 [    37  53000]
 [    24  58000]
 [    18  52000]
 [    22  81000]
 [    34  43000]
 [    31  34000]
 [    49  36000]
 [    27  88000]
 [    41  52000]
 [    27  84000]
 [    35  20000]
 [    43 112000]
 [    27  58000]
 [    37  80000]
 [    52  90000]
 [    26  30000]
 [    49  86000]
 [    57 122000]
 [    34  25000]
 [    35  57000]
 [    34 115000]
 [    59  88000]
 [    45  32000]
 [    29  83000]
 [    

In [11]:
print("\nTest Labels (y_test):")
print(y_test)


Test Labels (y_test):
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [12]:
# Feature Scaling
# Step 5: Standardize the feature values (Age, Estimated Salary)
# Why? Logistic Regression (and many ML models) perform better when features are on the same scale.
# Example: Age ranges from ~18–60, Salary ranges from ~20,000–150,000.
# Without scaling, Salary would dominate Age because of its larger numeric range.

from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
sc = StandardScaler()

# Fit the scaler on the training set and transform it
# fit_transform → learns the scaling parameters (mean, std) from X_train and applies them
X_train = sc.fit_transform(X_train)

# Use the same scaling parameters to transform the test set
# transform → applies the scaling learned from training data (important: never fit again on test data!)
X_test = sc.transform(X_test)

# Print the scaled values to see the transformation
print("Scaled Training Features (X_train):")
print(X_train)

print("\nScaled Test Features (X_test):")
print(X_test)

Scaled Training Features (X_train):
[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30

In [13]:
# Training the Logistic Regression model on the Training set
# Step 6: Create and train the Logistic Regression classifier

from sklearn.linear_model import LogisticRegression

# Initialize the Logistic Regression model
# random_state = 0 → ensures reproducibility (same results each run)
classifier = LogisticRegression(random_state = 0)

# Fit the model on the training data
# X_train → scaled features (Age, Salary)
# y_train → target labels (Purchased = 0 or 1)
classifier.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",0
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`multic

In [14]:
# Predicting a new result
# Step 7: Use the trained Logistic Regression model to predict for a new user
# Example: Age = 30, Estimated Salary = 87,000
# Important: We must apply the same scaling (sc.transform) before prediction
print(classifier.predict(sc.transform([[30, 87000]])))

[0]


##  Interpreting the Prediction Output

The model returned **[0]** for the input `(Age = 30, Estimated Salary = 87,000)`.

- Since this is a **binary classification problem** (`Purchased` = 0 or 1):
  - `0` → The model predicts the user **did not purchase** the product.
  - `1` → The model would predict the user **purchased** the product.
- The square brackets `[ ]` indicate that scikit-learn outputs results as an **array**, even if we predict for a single sample.

In this case, the Logistic Regression model classifies the new user into the **"Not Purchased"** category.


In [15]:
# Predicting the Test set results
# Step 8: Use the trained model to predict outcomes for the test set
y_pred = classifier.predict(X_test)

# Compare predicted results (y_pred) with actual results (y_test)
# np.concatenate → joins arrays side by side for easier comparison
# y_pred.reshape(len(y_pred),1) → reshape predictions into a column
# y_test.reshape(len(y_test),1) → reshape actual labels into a column
# The final output shows [Predicted, Actual] pairs for each test sample
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [16]:
# Making the Confusion Matrix
# Step 9: Evaluate the model performance

from sklearn.metrics import confusion_matrix, accuracy_score

# confusion_matrix → compares actual labels (y_test) with predicted labels (y_pred)
# Output format:
# [[TN, FP],
#  [FN, TP]]
# TN = True Negatives, FP = False Positives
# FN = False Negatives, TP = True Positives
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# accuracy_score → calculates the percentage of correct predictions
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix:
[[65  3]
 [ 8 24]]
Accuracy Score: 0.89


In [17]:
# Get probabilities instead of direct predictions
y_prob = classifier.predict_proba(X_test)[:, 1]  # probability of class 1 (Purchased)

In [19]:
# Adjust threshold (e.g., 0.4 instead of 0.5)
threshold = 0.4
y_pred_adjusted = (y_prob >= threshold).astype(int)

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [22]:
# Evaluate again
cm = confusion_matrix(y_test, y_pred_adjusted)
print("Confusion Matrix:\n", cm)
print("Accuracy:", accuracy_score(y_test, y_pred_adjusted))
print("Precision:", precision_score(y_test, y_pred_adjusted))
print("Recall:", recall_score(y_test, y_pred_adjusted))

Confusion Matrix:
 [[61  7]
 [ 5 27]]
Accuracy: 0.88
Precision: 0.7941176470588235
Recall: 0.84375


In [18]:
import gradio as gr
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# -----------------------------
# Step 1: Load your dataset
# -----------------------------
dataset = pd.read_csv("Social_Network_Ads.csv")

# Select features by column names
X = dataset[['Age', 'EstimatedSalary']].values
y = dataset['Purchased'].values

# -----------------------------
# Step 2: Train/Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# -----------------------------
# Step 3: Feature Scaling
# -----------------------------
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# -----------------------------
# Step 4: Train Logistic Regression
# -----------------------------
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

# -----------------------------
# Step 5: Define prediction function
# -----------------------------
def predict_purchase(age, salary):
    scaled_input = sc.transform([[age, salary]])
    prediction = classifier.predict(scaled_input)[0]
    return f"Prediction: {prediction} (0 = Not Purchased, 1 = Purchased)"

# -----------------------------
# Step 6: Build Gradio Interface
# -----------------------------
interface = gr.Interface(
    fn=predict_purchase,
    inputs=[
        gr.Slider(18, 60, step=1, label="Age", value=30),              # slider for age
        gr.Slider(15000, 150000, step=5000, label="Estimated Salary", value=87000)  # slider for salary
    ],
    outputs="text",
    title="Logistic Regression Purchase Prediction",
    description="Adjust Age and Estimated Salary to predict whether the user purchased (1) or not (0)."
)

# -----------------------------
# Step 7: Launch the app
# -----------------------------
interface.launch()

C:\Users\admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.
