In [1]:
# K-Nearest Neighbors (K-NN)
# This section sets up the environment for using the KNN algorithm.

# Importing the libraries
import numpy as np              # NumPy is used for numerical operations and handling arrays
import matplotlib.pyplot as plt # Matplotlib is used for plotting graphs and visualizing data
import pandas as pd             # Pandas is used for handling datasets in tabular form (rows and columns)

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')  
# Reads the CSV file into a Pandas DataFrame. 
# Each row represents one user’s record (Age, Estimated Salary, Purchased).

X = dataset.iloc[:, :-1].values  
# Selects all columns except the last one as features (Age and Salary). 
# .iloc[:, :-1] means “all rows, all columns except the last.”

y = dataset.iloc[:, -1].values  
# Selects the last column as the target variable (Purchased: 0 = No, 1 = Yes).
# .iloc[:, -1] means “all rows, only the last column.”

In [3]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split  

# train_test_split is a function that divides the dataset into two parts:
# - Training set: used to teach the model
# - Test set: used to evaluate how well the model performs on unseen data

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.25, random_state = 0
)
# test_size = 0.25 → 25% of the data goes into the test set, 75% into the training set
# random_state = 0 → ensures reproducibility (same split every time you run the code)

In [4]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler  

# StandardScaler standardizes features by removing the mean and scaling to unit variance.
# This ensures that Age and Salary are on the same scale, so distance calculations in KNN are fair.

sc = StandardScaler()  
# Creates a scaler object that will learn the mean and standard deviation from the training set.

X_train = sc.fit_transform(X_train)  
# Fits the scaler on the training data (learns mean & std) and transforms it.
# Result: Age and Salary values are standardized (mean = 0, std = 1).

X_test = sc.transform(X_test)  
# Uses the same scaler (from training set) to transform the test data.
# Important: We never fit again on test data, to avoid data leakage.

print(X_train)  # Shows the scaled training features
print(X_test)   # Shows the scaled test features

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 

In [5]:
# Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier  

# KNeighborsClassifier is the scikit-learn class for KNN.
# It classifies new data points based on the majority class of their nearest neighbors.

classifier = KNeighborsClassifier(
    n_neighbors = 5,   # K = 5 → the algorithm will look at the 5 closest neighbors
    metric = 'minkowski', # Minkowski is a general distance metric
    p = 2              # When p = 2, Minkowski becomes Euclidean distance (straight-line distance)
)

classifier.fit(X_train, y_train)  
# Fits the classifier on the training data.
# The model now "stores" the training points and will use them to predict new cases.

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [9]:
# Predicting a new result
print(classifier.predict(sc.transform([[30, 87000]])))
# Explanation:
# - We want to predict whether a person aged 30 with a salary of 87,000 will purchase or not.
# - [[30, 87000]] is the new data point (Age = 30, Salary = 87,000).
# - sc.transform(...) scales this new data point using the same scaler fitted on training data.
#   This ensures the new input is on the same scale as the training set.
# - classifier.predict(...) applies the KNN model to predict the outcome.
# - Output will be [0] or [1]:
#     0 → Not Purchased
#     1 → Purchased

[0]


In [11]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


In [10]:
# Predicting a new result
print(classifier.predict(sc.transform([[30, 87000]])))
# Explanation:
# - We want to predict whether a person aged 30 with a salary of 87,000 will purchase or not.
# - [[30, 87000]] is the new data point (Age = 30, Salary = 87,000).
# - sc.transform(...) scales this new data point using the same scaler fitted on training data.
#   This ensures the new input is on the same scale as the training set.
# - classifier.predict(...) applies the KNN model to predict the outcome.
# - Output will be [0] or [1]:
#     0 → Not Purchased
#     1 → Purchased


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score  

# confusion_matrix compares the actual test labels (y_test) with the predicted labels (y_pred).
# It shows how many predictions were correct (True Positives & True Negatives)
# and how many were wrong (False Positives & False Negatives).

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
# Prints the confusion matrix as a 2x2 table:
# [[TN, FP],
#  [FN, TP]]

accuracy_score(y_test, y_pred)  
# Calculates the overall accuracy of the model:
# Accuracy = (Correct Predictions) / (Total Predictions)


[0]
[[64  4]
 [ 3 29]]


0.93

- TN = 64 → 64 people correctly predicted as Not Purchased

- FP = 4 → 4 people wrongly predicted as Purchased when they actually didn’t

- FN = 3 → 3 people wrongly predicted as Not Purchased when they actually did purchase

- TP = 29 → 29 people correctly predicted as Purchased

# 🧭 Pro Tips for Understanding K-Nearest Neighbors (KNN)

KNN is one of the simplest yet powerful algorithms in machine learning.  
Here’s how to make sense of the entire workflow we coded step by step:

---

## 1. Importing Libraries
- **NumPy** → Math toolbox (arrays, calculations).
- **Matplotlib** → Drawing board (plots, charts).
- **Pandas** → Spreadsheet manager (datasets in rows & columns).

👉 *Tip:* Always know which library does what — it helps you debug faster.

---

## 2. Loading the Dataset
- `X` = Features (Age, Salary).  
- `y` = Target (Purchased or Not).  

👉 *Tip:* Think of `X` as the **questions** and `y` as the **answers**.

---

## 3. Splitting into Training & Test Sets
- Training set → Model learns patterns.  
- Test set → Model proves itself.  

👉 *Tip:* This is like practicing before an exam and then sitting for the real test.

---

## 4. Feature Scaling
- KNN relies on **distance**.  
- If features are on different scales (Age in years vs. Salary in thousands), one feature dominates.  
- Scaling ensures fair comparison.  

👉 *Tip:* Always scale before using KNN, otherwise results can be misleading.

---

## 5. Training the KNN Model
- `n_neighbors = 5` → Look at 5 closest points.  
- `metric = 'minkowski', p = 2` → Euclidean distance.  
- KNN doesn’t build a formula, it just **remembers the training data**.

👉 *Tip:* Choosing `K` is crucial:
- Small K → sensitive to noise.  
- Large K → smoother but may ignore local patterns.

---

## 6. Predicting New Results
- Input a new data point (Age = 30, Salary = 87,000).  
- Scale it → Compare with training data → Majority vote decides.  

 *Tip:* Always transform new inputs with the same scaler used on training data.

---

## 7. Confusion Matrix & Accuracy
- Confusion Matrix shows **types of predictions**:
  - TN → Correctly predicted Not Purchased.
  - FP → Wrongly predicted Purchased.
  - FN → Wrongly predicted Not Purchased.
  - TP → Correctly predicted Purchased.
- Accuracy = (TN + TP) / Total predictions.

 *Tip:* Don’t rely only on accuracy. Look at **Precision** and **Recall** to understand the model’s strengths and weaknesses.

---

##  Big Picture
- KNN is like asking your neighbors for advice, the majority opinion decides the prediction.
- It’s simple, intuitive, and great for small datasets.
- Scaling and choosing the right `K` are the keys to success.

---

**Trainer one-liner for students:**  
*KNN predicts by looking at the closest neighbors, like asking your friends for advice. The majority vote decides the outcome.*


#  Precision vs Recall in KNN (Which to Pick?)

When evaluating a KNN model, we often ask: should we care more about **Precision** or **Recall**?  
The answer depends on the business problem and the cost of mistakes.

---

## Definitions
- **Precision** = TP / (TP + FP)  
  → Of all the people we predicted as "Purchased," how many actually purchased?  
  → Focuses on **avoiding false alarms**.

- **Recall** = TP / (TP + FN)  
  → Of all the people who actually purchased, how many did we correctly predict?  
  → Focuses on **catching as many positives as possible**.

---

## In Our Dataset (Customer Purchase Prediction)
- **False Positive (FP):** Predicting someone will purchase when they won’t.  
  → Cost: Wasted marketing effort (sending offers to uninterested customers).  

- **False Negative (FN):** Predicting someone won’t purchase when they actually will.  
  → Cost: Missed opportunity (losing a potential buyer).  

---

## Which Matters More?
- In marketing and sales, **Recall is usually more important**.  
  - Missing a buyer (FN) means losing revenue.  
  - A few false alarms (FP) are acceptable because sending an extra offer is cheaper than missing a sale.  

- In fraud detection or spam filtering, **Precision is more important**.  
  - False alarms (FP) are costly because they wrongly flag genuine customers or emails.  

---

## For Our Case (Social Network Ads → Purchase Prediction)
- **We prioritize Recall**:  
  - Better to catch more potential buyers, even if we sometimes predict a few non-buyers as buyers.  
  - This ensures we maximize sales opportunities.  

---

### Pro Tip for Students
*Think about the real-world cost of mistakes. If missing positives is worse, choose Recall. If false alarms are worse, choose Precision. Accuracy alone is not enough  always ask which metric aligns with the business goal.*
