# Naive Bayes Classifier

## Intuition
- Naive Bayes is a **probabilistic classifier** built on Bayes’ Theorem.  
- It assumes that features (like Age and Salary) are **conditionally independent** given the class label.  
- Despite this “naive” assumption, it often performs very well in practice, especially for text classification and categorical data.

---

## Bayes’ Theorem Refresher


\[
P(Class \mid Features) = \frac{P(Features \mid Class) \cdot P(Class)}{P(Features)}
\]



- **Prior (P(Class))** → How common each class is in the dataset.  
- **Likelihood (P(Features | Class))** → Probability of seeing the features given the class.  
- **Evidence (P(Features))** → Same for all classes, ignored when comparing.  
- **Posterior (P(Class | Features))** → Final probability we compare to decide the class.

Naive Bayes predicts the class with the **highest posterior probability**.

---

## Theory Example (Student Pass/Fail)

### Dataset Attributes
- Year: First Year / Second Year  
- Gender: Male / Female  
- Subject: S1 / S2  
- Result: Pass / Fail  

### Query
*First‑year female student taking Subject S1 → Will she pass or fail?*

### Step 1: Prior Probabilities
- P(Pass) = 0.5  
- P(Fail) = 0.5  

### Step 2: Conditional Probabilities
- P(First Year | Pass) = 0.6  
- P(First Year | Fail) = 0.4  
- P(Female | Pass) = 0.2  
- P(Female | Fail) = 0.6  
- P(S1 | Pass) = 0.4  
- P(S1 | Fail) = 0.6  

### Step 3: Posterior Probabilities
- P(Pass | Query) ∝ 0.5 × 0.6 × 0.2 × 0.4 = **0.024**  
- P(Fail | Query) ∝ 0.5 × 0.4 × 0.6 × 0.6 = **0.072**  

Prediction = **Fail** (since 0.072 > 0.024).

---

#  Naive Bayes Classifier: Student Pass/Fail Example

##  Problem Setup
- Dataset attributes: **Year (First/Second), Gender (Male/Female), Subject (S1/S2), Result (Pass/Fail)**  
- Query: *Predict whether a First‑year Female student taking Subject S1 will Pass or Fail.*

---

##  Step 1: Calculate Priors
- Out of 10 students: 5 passed, 5 failed.  
- P(Pass) = 5/10 = 0.5  
- P(Fail) = 5/10 = 0.5  

 Before considering features, both outcomes are equally likely.

---

## Step 2: Calculate Conditional Probabilities
We compute probabilities of each feature given the class:

- **Year (First Year):**  
  - P(First Year | Pass) = 3/5 = 0.6  
  - P(First Year | Fail) = 2/5 = 0.4  

- **Gender (Female):**  
  - P(Female | Pass) = 1/5 = 0.2  
  - P(Female | Fail) = 3/5 = 0.6  

- **Subject (S1):**  
  - P(S1 | Pass) = 2/5 = 0.4  
  - P(S1 | Fail) = 3/5 = 0.6  

---

##  Step 3: Apply Naive Bayes Formula
We multiply the prior with all conditional probabilities for each class.

- For **Pass**:  
  P(Pass | Query) ∝ 0.5 × 0.6 × 0.2 × 0.4 = **0.024**

- For **Fail**:  
  P(Fail | Query) ∝ 0.5 × 0.4 × 0.6 × 0.6 = **0.072**

---

##  Step 4: Final Decision
- Compare posterior probabilities:  
  - P(Pass | Query) = 0.024  
  - P(Fail | Query) = 0.072  

Since 0.072 > 0.024, the classifier predicts **Fail**.

---


## Summary Table of Probabilities


| Attribute         | P(⋅ | Pass) | P(⋅ | Fail) |
|-------------------|------------|-------------|
| Year = First Year | 0.6        | 0.4         |
| Gender = Female   | 0.2        | 0.6         |
| Subject = S1      | 0.4        | 0.6         |
| Prior Probability | 0.5        | 0.5         |

---


## Key Insight
- Naive Bayes multiplies the **prior probability** with the **likelihoods of each feature**.  
- The class with the higher product (posterior probability) is chosen.  
- Even if the exact combination doesn’t exist in the dataset, Naive Bayes can still make a prediction using available probabilities.

---

**Quick knows**  
*Naive Bayes is like stacking the odds from each clue (Year, Gender, Subject) and picking the side with the stronger combined probability.*

# Naive Bayes Classification Practice (Social Network Ads Dataset)

## Dataset Overview
We are predicting whether a person will **purchase (Yes=1 / No=0)** based on:
- **Age**
- **Estimated Salary**

### Sample Data
| Age | EstimatedSalary | Purchased |
|-----|----------------|-----------|
| 19  | 19000          | 0 |
| 35  | 20000          | 0 |
| 26  | 43000          | 0 |
| 27  | 57000          | 0 |
| 19  | 76000          | 0 |
| 27  | 58000          | 0 |
| 27  | 84000          | 0 |
| 32  | 150000         | 1 |
| 25  | 33000          | 0 |
| 35  | 65000          | 0 |

### Class Distribution (Training Set)
- Purchased = **0 (No)** → 189 samples  
- Purchased = **1 (Yes)** → 111 samples  
- Total = 300 samples  

Dataset is **imbalanced** (more “No Purchase” cases).

---

## How Naive Bayes Works Here

1. **Prior Probabilities**  
   - P(No Purchase) = 189/300 ≈ 0.63  
   - P(Purchase) = 111/300 ≈ 0.37  
   - The model starts with this imbalance: it expects “No Purchase” more often.

2. **Likelihoods (Feature Distributions)**  
   - For numeric features (Age, Salary), Naive Bayes assumes each class follows a **Gaussian (normal) distribution**.  
   - It estimates mean and variance of Age and Salary separately for “Purchase=0” and “Purchase=1”.  
   - Example:  
     - Age distribution for buyers vs non‑buyers.  
     - Salary distribution for buyers vs non‑buyers.

3. **Posterior Probabilities**  
   - For a new person, the model calculates:  
     

\[
     P(Purchase=Yes \mid Age, Salary) \propto P(Purchase=Yes) \cdot P(Age \mid Yes) \cdot P(Salary \mid Yes)
     \]

  
     

\[
     P(Purchase=No \mid Age, Salary) \propto P(Purchase=No) \cdot P(Age \mid No) \cdot P(Salary \mid No)
     \]

  
   - The class with the higher probability is chosen.

4. **Decision Boundary**  
   - The model effectively draws a boundary in the Age–Salary space.  
   - Points on one side are classified as “Purchase=Yes”, the other side as “No”.

---

## Effect of Imbalance
- Since **No Purchase** is more common, its prior probability is higher (0.63 vs 0.37).  
- This means the model is slightly biased towards predicting “No Purchase”.  
- However, if Age and Salary strongly match the buyer distribution, the likelihood terms can outweigh the prior.  
- Example: A person with very high salary (like 150,000) shifts the probability towards “Purchase=Yes” despite the imbalance.

---

## Key Insights
- Naive Bayes combines **prior probabilities** (class distribution) with **feature likelihoods** (Age, Salary distributions).  
- Imbalance in the dataset makes the model more cautious about predicting “Purchase=Yes”.  
- The confusion matrix often shows more **False Negatives** (missed buyers) because of this imbalance.  
- Business interpretation:  
  - **False Negatives** → lost sales opportunities.  
  - **False Positives** → wasted marketing effort.  
- Which error matters more depends on business goals.

---

**Quick note:**  
*Naive Bayes starts with the prior odds (more non‑buyers), then adjusts using Age and Salary likelihoods, if the features look like a buyer, the model can overcome the imbalance.*


In [8]:
# Importing the libraries
import numpy as np              # For numerical operations and arrays
import matplotlib.pyplot as plt # For plotting graphs and visualizations
import pandas as pd             # For handling datasets and dataframes

In [9]:
# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')   # Load the CSV file into a pandas DataFrame

# Separating features and target
# X contains the independent variables (Age and EstimatedSalary)
X = dataset.iloc[:, :-1].values

# y contains the dependent variable (Purchased: 0 = No, 1 = Yes)
y = dataset.iloc[:, -1].values

In [10]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

# Divide the dataset into training (75%) and test (25%) sets
# random_state ensures reproducibility of the split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

# Print the training and test sets to verify the split
print("X_train:\n", X_train)   # Features for training
print("y_train:\n", y_train)   # Labels for training
print("X_test:\n", X_test)     # Features for testing
print("y_test:\n", y_test)     # Labels for testing


X_train:
 [[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]
 [    35  25000]
 [    35  50000]
 [    42  73000]
 [    47  49000]
 [    59  29000]
 [    49  65000]
 [    45 131000]
 [    31  89000]
 [    46  82000]
 [    47  51000]
 [    26  15000]
 [    60 102000]
 [    38 112000]
 [    40 107000]
 [    42  53000]
 [    35  59000]
 [    48  41000]
 [    48 134000]
 [    38 113000]
 [    29 148000]
 [    26  15000]
 [    60  42000]
 [    24  19000]
 [    42 149000]
 [    46  96000]
 [    28  59000]
 [    39  96000]
 [    28  89000]
 [    41  72000]
 [    45  26000]
 [    33  69000]
 [    20  82000]
 [    31  74000]
 [    42  80000]
 [    35  72000]
 [    33 149000]
 [    40  71000]
 [    51 146000]
 [    46  79000]
 [    35  75000]
 [    38  51000]
 [    36  75000]
 [    37  78000]
 [    38  61000]
 [    60 108000]
 [    20  82000]
 [    57  74000]
 [    42  65000]
 [  

In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
sc = StandardScaler()

# Fit the scaler on the training data and transform it
# "fit" calculates the mean and standard deviation of X_train
# "transform" uses those values to scale the data
X_train = sc.fit_transform(X_train)

# For the test set, we only use "transform"
# This ensures the test data is scaled using the same parameters
# as the training data (mean and std from training set)
X_test = sc.transform(X_test)

# Print scaled values to check
print("Scaled Training Features:\n", X_train)
print("Scaled Test Features:\n", X_test)


Scaled Training Features:
 [[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 

In [12]:
# Training the Naive Bayes model on the Training set

# Import Gaussian Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB

# Create the classifier object
classifier = GaussianNB()

# Fit the model on the training data
# This step makes the model learn the relationship between
# Age, EstimatedSalary (features) and Purchased (target)
classifier.fit(X_train, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [13]:
# Predicting a new result

# Here we predict whether a person with Age=30 and EstimatedSalary=87000 will purchase or not.
# We must scale the input using the same StandardScaler (sc) used for training.
# Then we pass the scaled values to the classifier for prediction.

print(classifier.predict(sc.transform([[30, 87000]])))

[0]


In [14]:
# Predicting the Test set results

# Use the trained classifier to predict outcomes for the test set
y_pred = classifier.predict(X_test)

# Compare predictions (y_pred) with actual labels (y_test)
# np.concatenate merges them side by side for easy comparison
# Left column = predicted values, Right column = actual values
print(np.concatenate(
    (y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 
    axis=1
))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


In [15]:
# Making the Confusion Matrix

# Import metrics for evaluation
from sklearn.metrics import confusion_matrix, accuracy_score

# Build the confusion matrix to compare predictions vs actual labels
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:\n", cm)

# Calculate and display the accuracy score
print("Accuracy:", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[65  3]
 [ 7 25]]
Accuracy: 0.9



- **65** → True Negatives (correctly predicted No Purchase)  
- **3** → False Positives (predicted Purchase but actually No Purchase)  
- **7** → False Negatives (predicted No Purchase but actually Purchase)  
- **25** → True Positives (correctly predicted Purchase)  

---

##  Accuracy : Accuracy: 0.90

 The model correctly classified **90% of the test set**.

---

## Interpretation
- The classifier performs well overall, with high accuracy.  
- Slight imbalance in the dataset (more “No Purchase” cases) makes the model lean towards predicting **No Purchase**.  
- **False Negatives (7)** → missed buyers, which could mean lost sales opportunities.  
- **False Positives (3)** → predicted buyers who wouldn’t actually purchase, leading to wasted marketing effort.  

---

##  Key Insight
Naive Bayes combines prior probabilities (class distribution) with feature likelihoods (Age, Salary).  
Even with imbalance, the model achieves strong accuracy, but business decisions should consider whether **missing buyers** or **mis‑targeting non‑buyers** is more costly.




## What’s Happening
- We want to predict **Purchase (Yes=1 / No=0)** using Age and Salary.
- In the training set:
  - **No Purchase (0)** → 189 samples
  - **Purchase (1)** → 111 samples
- This means the dataset is **imbalanced**: more "No Purchase" cases.

---

## How the Model Thinks
1. **Start with Prior Odds**
   - The model first looks at how often each class appears.
   - Since "No Purchase" is more common (63%), the model leans toward predicting **No** by default.

2. **Look at Feature Patterns**
   - It then checks Age and Salary patterns for each group.
   - Example:
     - Buyers often have higher salaries or certain age ranges.
     - Non‑buyers cluster around lower salaries or younger ages.

3. **Combine Both**
   - If a new person’s Age/Salary looks similar to past buyers, the model can still predict **Yes**, even though "No" is more common.
   - If the features don’t strongly match the buyer group, the model sticks with **No**.

---

## Impact of Imbalance
- Because "No Purchase" is the majority, the model is **biased toward predicting No**.
- This shows up in the results:
  - It correctly catches most non‑buyers.
  - It sometimes **misses buyers** (False Negatives).
- Example confusion matrix:

-     [[65  3]
-     [ 7 25]]


- 65 → Correctly said "No Purchase"
- 25 → Correctly said "Purchase"
- 7 → Missed buyers (predicted No but actually Yes)
- 3 → Predicted Yes but actually No

---

## Key Takeaway
- Naive Bayes doesn’t “fix” imbalance, it reflects it in the prior odds.
- The model will **favor the majority class** unless the features (Age, Salary) strongly indicate otherwise.
- That’s why accuracy looks good (90%), but you still see **missed buyers**.
- In business terms:
- **False Negatives (missed buyers)** → lost sales.
- **False Positives (wrongly targeted)** → wasted marketing.

---

**Simple analogy:**  
Think of it like guessing cricket match outcomes. If Team A wins 63% of past games, you’ll usually bet on Team A. But if you see Team B has star players (features like high salary/age patterns), you might switch your bet. That’s exactly how Naive Bayes balances prior odds with feature evidence.

