* NumPy library is an important foundational tool for studying Machine Learning. Many of its functions are very useful for performing any mathematical or scientific calculation. As it is known that mathematics is the foundation of machine learning, most of the mathematical tasks can be performed using NumPy.

**Introduction to NumPy**
NumPy stands for ‘Numerical Python’. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices.

**Why Numpy?**
* It's Fast
* Behind the scenes optimization written in C
* Vectorization via brodcasting (Avoiding Loops)
* Backbone of other Python Scientific packages

**What are we going to Cover?**
* Most Useful functions
* Numpy datatypes & attributes (ndarray)
* Creatingg Arrays
* Viewing arrays & matrices
* Manupulating & comparing Arrays
* Sorting Arrays
* Use cases

# 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
print(a)

[1 2 3]


array([1 2 3]):
* Names: Array, Vector
* 1 - dimensional
* shape = (1,3)

In [4]:
# Check the type of a 
type(a)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
print(a2)

[[1.  2.  3.3]
 [4.  5.  6.5]]


[[1.  2.  3.3]
 [4.  5.  6.5]]

* Names: Array, Matrix
* More than 1-dimension
* Shape = (2,3)

In [8]:

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


* Names: Array, Matrix
* More than 1-dimension
* Shape = (2,3,3)

In [15]:
# Dimensions
a.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
# Check the data arrtibutes
a.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [19]:
# Check the Shapes 
a.shape

(3,)

In [20]:
a2.shape

(2, 3)

In [21]:
a2.shape

(2, 3)

In [23]:
# What kind of types we have 
type(a)

numpy.ndarray

In [24]:
type(a2)

numpy.ndarray

In [25]:
type(a3)

numpy.ndarray

In [27]:
# Creata a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Arrays

In [28]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int32')

In [35]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [36]:
ones.dtype

dtype('float64')

In [37]:
type(ones)

numpy.ndarray

In [38]:
zeros = np.zeros((2,2))

In [39]:
zeros

array([[0., 0.],
       [0., 0.]])

In case, you could imagine zeros is kind of like a placeholder array, maybe in machine learning. You want to fill an array with some initial data or that data you don't know yet. So you create just to work out the shapes of data you're working with.

make sure shapes while creating arrays 

In [40]:
range_array = np.arange(0,10,1)

starting from : 0
ending at : 10
step size : 1 

In [43]:
# Create random array
random_array = np.random.randint(0,10, size = (3,5))
random_array

array([[4, 6, 4, 6, 6],
       [2, 9, 0, 7, 9],
       [5, 7, 2, 1, 2]])

In [45]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.92957788, 0.74009672, 0.35319372],
       [0.61784758, 0.32934311, 0.57305763],
       [0.32227139, 0.35296601, 0.97567607],
       [0.42910546, 0.74125531, 0.09914364],
       [0.74677156, 0.64689953, 0.72194236]])

In [47]:
random_array_2.shape

(5, 3)

# Numpy random seed 

To get the exact same result with the same notebook, it is good way to use seed. The other person can get the same results which you get from the data by useing seed, with same code

In [52]:
np.random.seed(seed = 40)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[6, 7, 5],
       [8, 8, 2],
       [1, 7, 2],
       [3, 7, 3],
       [9, 0, 1]])

In [ ]:
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4