* NumPy library is an important foundational tool for studying Machine Learning. Many of its functions are very useful for performing any mathematical or scientific calculation. As it is known that mathematics is the foundation of machine learning, most of the mathematical tasks can be performed using NumPy.

**Introduction to NumPy**
NumPy stands for ‘Numerical Python’. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices.

**Why Numpy?**
* It's Fast
* Behind the scenes optimization written in C
* Vectorization via brodcasting (Avoiding Loops)
* Backbone of other Python Scientific packages

**What are we going to Cover?**
* Most Useful functions
* Numpy datatypes & attributes (ndarray)
* Creatingg Arrays
* Viewing arrays & matrices
* Manupulating & comparing Arrays
* Sorting Arrays
* Use cases

# 1. DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
print(a)

[1 2 3]


array([1 2 3]):
* Names: Array, Vector
* 1 - dimensional
* shape = (1,3)

In [4]:
# Check the type of a 
type(a)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
print(a2)

[[1.  2.  3.3]
 [4.  5.  6.5]]


[[1.  2.  3.3]
 [4.  5.  6.5]]

* Names: Array, Matrix
* More than 1-dimension
* Shape = (2,3)

In [8]:

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


* Names: Array, Matrix
* More than 1-dimension
* Shape = (2,3,3)

In [15]:
# Dimensions
a.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
# Check the data arrtibutes
a.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [19]:
# Check the Shapes 
a.shape

(3,)

In [20]:
a2.shape

(2, 3)

In [21]:
a2.shape

(2, 3)

In [23]:
# What kind of types we have 
type(a)

numpy.ndarray

In [24]:
type(a2)

numpy.ndarray

In [25]:
type(a3)

numpy.ndarray

In [26]:
# Creata a dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5